default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: blog_app_development
  username: ENV['DB_USER']
  password: ENV['DB_PASSWORD']

test:
  <<: *default
  database: blog_app_test
  username: ENV['DB_USER']
  password: ENV['DB_PASSWORD']

# production:
#   <<: *default
#   database: blog_app_production
#   username: username
#   password: password
