default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: blog_app_development
  username: dipendra
  password:

test:
  <<: *default
  database: blog_app_test
  username: dipendra
  password: 

# production:
#   <<: *default
#   database: blog_app_production
#   username: username
#   password: password
